const GET_GRAPH_DATA_SAGA = 'GET_GRAPH_DATA_SAGA';
const SET_GRAPH_DATA = 'SET_GRAPH_DATA';
const GRAPH_TYPE_LINE_CHART = 0;
const GRAPH_TYPE_BAR_CHART = 1;

export {
  GET_GRAPH_DATA_SAGA,
  SET_GRAPH_DATA,
  GRAPH_TYPE_LINE_CHART,
  GRAPH_TYPE_BAR_CHART
};
