const GET_USERS_SAGA = 'GET_USERS_SAGA';
const GET_GRAPH_DATA_SAGA = 'GET_GRAPH_DATA_SAGA';
const SET_USERS = 'SET_USERS';
const SET_GRAPH_DATA = 'SET_GRAPH_DATA';

export {  //eslint-disable-line
  GET_USERS_SAGA,
  SET_USERS,
  GET_GRAPH_DATA_SAGA,
  SET_GRAPH_DATA
};
