const GRAPH_TYPE_LINE_CHART = 0
const GRAPH_TYPE_BAR_CHART = 1
const NO_GRAPH_DATA_MESSAGE = 'There is no data to display.'

export { GRAPH_TYPE_LINE_CHART, GRAPH_TYPE_BAR_CHART, NO_GRAPH_DATA_MESSAGE }
